<div class="block-banner banner-a style-2">
    <div class="grid-fluid">
        <h2 class="banner-title"><a href="#" title="Never Boring. Totally Reliable.">Never Boring. Totally Reliable.</a>
        </h2>
        <div data-slick-slider="{&quot;typeSlide&quot;: &quot;services&quot;, &quot;isNotInitDesktop&quot;: true}" class="slider list-items-banner block-center-3">
            <div class="item">
                <div class="thumbnail style-2"><a href="<?php echo $block->getUrl('assistance/warranty') ?>" title="Lifetime Warranty" class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerA-Lifetime-Warranty.jpg'); ?>" alt="image"/></a>
                    <div class="description">
                        <p class="title"><a href="<?php echo $block->getUrl('assistance/warranty') ?>" title="Lifetime Warranty">Lifetime Warranty</a>
                        </p>
                        <div class="tinymce-editor">
                            <p>Some things really are forever. Shop confidently.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="thumbnail style-2"><a href="<?php echo $block->getUrl('assistance/return') ?>" title="100-Day Returns" class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerA-100-Day-Returns.jpg'); ?>" alt="image"/></a>
                    <div class="description">
                        <p class="title"><a href="<?php echo $block->getUrl('assistance/return') ?>" title="100 Day Returns">100 Day Returns</a>
                        </p>
                        <div class="tinymce-editor">
                            <p>Commitment Issues? We get it. Take it slow.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="thumbnail style-2"><a href="<?php echo $block->getUrl('services') ?>" title="Concierge Services" class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerA-Concierge-Service.jpg'); ?>" alt="image"/></a>
                    <div class="description">
                        <p class="title"><a href="<?php echo $block->getUrl('services') ?>" title="Concierge Services">Concierge Services</a>
                        </p>
                        <div class="tinymce-editor">
                            <p>From engraving to picking that perfect gift, we’ve got you.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>