<div class="block-banner banner-c style-3">
    <div class="grid-fluid">
        <div class="thumbnail"><a href="#" title="Irreverent Pieces. Incredible Style." class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerC-Style.jpg'); ?>" alt="image"/></a>
        </div>
        <h2 class="banner-title"><a href="#" title="Irreverent Pieces. Incredible Style.">Irreverent Pieces. Incredible Style.</a>
        </h2>
        <p><a href="#" title="Our taste is fresh, but we’re suckers for old school service - especially when paired with modern convenience. That’s why we curated an incredible slate of the best designer fine jewelry brands, all in one oh-so-awesome place, matched with tips for chic styling and thoughtful and innovative service you won’t find anywhereelse.">Our taste is fresh, but we’re suckers for old school service - especially when paired with modern convenience. That’s why we curated an incredible slate of the best designer fine jewelry brands, all in one oh-so-awesome place, matched with tips for chic styling and thoughtful and innovative service you won’t find anywhereelse.</a>
        </p>
    </div>
</div>