<div class="block-banner banner-b style-3">
    <div class="grid-fluid">
        <div class="thumbnail"><a href="#" title="You do you. We do the rest." class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerB-Ampersand.jpg'); ?>" alt="image"/></a>
        </div>
        <h2 class="banner-title"><a href="#" title="You do you. We do the rest.">You do you. We do the rest.</a>
        </h2>
        <p><a href="#" title="Experience Expertly-Selected jewelry, 100-Day Returns, and Anything-But-Basic Designers, all at Stone &amp; Strand.">Experience Expertly-Selected jewelry, 100-Day Returns, and Anything-But-Basic Designers, all at Stone & Strand.</a>
        </p>
    </div>
</div>