<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Sales\Block\Order\Totals
 * @see \Magento\Sales\Block\Order\Totals
 */
?>
<?php foreach ($block->getTotals() as $_code => $_total): ?>
    <?php if ($_total->getBlockName()): ?>
        <?php echo $block->getChildHtml($_total->getBlockName(), false); ?>
    <?php else: ?>
        <tr class="<?php /* @escapeNotVerified */ echo $_code; ?>">
            <th <?php /* @escapeNotVerified */ echo $block->getLabelProperties(); ?> scope="row">
                <?php if ($_total->getStrong()): ?>
                    <strong><?php echo $block->escapeHtml($_total->getLabel()); ?></strong>
                <?php else: ?>
                    <?php echo $block->escapeHtml($_total->getLabel()); ?>
                <?php endif ?>
            </th>
            <td class="currency" data-th="<?php echo $block->escapeHtml($_total->getLabel()); ?>">
                <?php /* @escapeNotVerified */ echo $_total->getCurrencyCode(); ?> <?php /* @escapeNotVerified */ echo $block->currencySymbol(); ?>
            </td>
            <td <?php /* @escapeNotVerified */ echo $block->getValueProperties(); ?> data-th="<?php echo $block->escapeHtml($_total->getLabel()); ?>">
                <?php if ($_total->getStrong()): ?>
                    <strong><span class="price"><?php /* @escapeNotVerified */ echo number_format($_total->getValue(), 2); ?></span></strong>
                <?php else: ?>
                    <span class="price"><?php /* @escapeNotVerified */ echo number_format($_total->getValue(), 2); ?></span>
                <?php endif; ?>
            </td>
        </tr>
    <?php endif; ?>
<?php endforeach; ?>
