<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Rma\Block\Email\Items */
?>

<?php foreach ($block->getCollection() as $item): ?>
<tr>
    <td align="left">
        <p style="color: #000000; font-size: 16px; font-family: OpenSans-Regular, Verdana, sans-serif; margin: 0; line-height: 28px; letter-spacing: 1px">
            <?php
                echo '- ' . $block->escapeHtml($item->getProductName());
                if ($_options = $item->getOptions()){
                    echo ' - ';
                    $count = count($item->getOptions());
                    $i = 0;
                    foreach ($_options as $_option){
                        $i ++;
                        if ($i != $count){
                            echo $_option['label'] . ' ' . $_option['value'] . ', ';
                        }else{
                            echo $_option['label'] . ' ' . $_option['value'];
                        }
                    }
                }
            ?>
        </p>
    </td>
</tr>
<?php endforeach; ?>