<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>

<?php if ($block->getProductCollection() && $block->getProductCollection()->getSize()): ?>
    <?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    ?>
    <div class="col-md-4">
        <div class="new-block">
            <?php if ($title): ?>
                <h2 class="line-title">
                    <a href="<?php echo $block->getLink(); ?>" title="<?php echo $title; ?>"><span><?php echo $title; ?></span></a>
                </h2>
            <?php endif ?>

            <div data-slick-slider="{&quot;typeSlide&quot;: &quot;news&quot;}" class="slider new-slider">
                <?php foreach ($items as $_item): ?>
                    <?php
                    $productUrl = $block->getProductUrl($_item);
                    $productName = $block->escapeHtml($_item->getName());
                    $designer = $block->getDesignerById($_item->getSsDesigner());
                    $designerName = ($designer) ? $designer->getName() : '';
                    $designerUrl = ($designer) ? $designer->getUrl() : '#';
                    ?>
                    <div class="item">
                        <div class="thumbnail text-center">
                            <a href="<?php echo $productUrl; ?>" title="<?php echo $productName; ?>" class="image">
                                <?php echo $block->getImage($_item, 'homepage_product_new')->toHtml(); ?>
                            </a>
                            <div class="description">
                                <p class="material">
                                    <a href="<?php echo $productUrl ?>" title="<?php echo $productName ?>"><?php echo $productName ?></a>
                                </p>
                                <?php if ($designer): ?>
                                    <p class="author">
                                        <a href="<?php echo $designerUrl; ?>" title="<?php echo $designerName; ?>"><?php echo $designerName; ?></a>
                                    </p>
                                <?php endif; ?>
                                <?php echo $block->getProductPriceHtml($_item, $type); ?>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php

 endif;
