<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
/** @var \Magento\Catalog\Api\CategoryManagementInterface $obj */
$themeHelper = $objectManager->create('\Ss\Theme\Helper\Data');

// get extension facebook pixel
$registry = $objectManager->get('\Magento\Framework\Registry');
$fbq = $registry->registry('facebook_pixel');
?>
<div class="row">
    <div class="col-md-3 col-md-push-9">
        <div class="follow-us">
            <p class="title">Follow us</p>
            <ul class="social-block">
                <li><a target="_blank" href="<?php echo $themeHelper->getUrlSocialInstagram() ?>" title="Instagram" class="icon icon-instagram"></a>
                </li>
                <li><a target="_blank" href="<?php echo $themeHelper->getUrlSocialFacebook() ?>" title="Facebook" class="icon icon-facebook"></a>
                </li>
                <li><a target="_blank" href="<?php echo $themeHelper->getUrlSocialTwitter() ?>" title="Twitter" class="icon icon-twitter"></a>
                </li>
                <li><a target="_blank" href="<?php echo $themeHelper->getUrlSocialPin() ?>" title="Pinterest" class="icon icon-pinterest"></a>
                </li>
            </ul>
        </div>
        <div class="subscribe-block">
            <p class="title"><?php echo __('News &amp; special offers') ?></p>
            <?php echo $block->getChildHtml("ss.footer.newsletter"); ?>
        </div>
    </div>


    <div data-collapse="{&quot;isToggleAll&quot;: true, &quot;notRunOn&quot;: &quot;desktop&quot;, &quot;numItemOpenDefault&quot;: [1,2,3,4,5]}" class="col-md-9 col-md-pull-3 sitemap-block">
        <div class="items items-left">
            <div class="row-1">
                <div data-item class="col-md-4">
                    <?php echo $block->getChildHtml("ss.footer.aboutUs"); ?>
                </div>
                <div data-item class="col-md-4">
                    <?php echo $block->getChildHtml("ss.footer.information"); ?>
                </div>
                <div data-item class="col-md-4">
                    <?php echo $block->getChildHtml("ss.footer.contactUs"); ?>
                </div>
            </div>
        </div>
        <div class="items items-right">
            <div class="row-1">
                <div data-item class="col-md-6">
                    <?php echo $block->getChildHtml("ss.footer.assistance"); ?>
                </div>
                <div data-item class="col-md-6">
                    <?php echo $block->getChildHtml("ss.footer.services"); ?>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- begin SnapEngage code-->
    <script>
      (function() {
        var se = document.createElement('script'); se.type = 'text/javascript'; se.async = true;
        se.src = '//storage.googleapis.com/code.snapengage.com/js/5e55d214-a227-47ae-b1a3-cce17ac8b509.js';
        var done = false;
        se.onload = se.onreadystatechange = function() {
          if (!done&&(!this.readyState||this.readyState==='loaded'||this.readyState==='complete')) {
            done = true;
            /* Place your SnapEngage JS API code below */
            /* SnapEngage.allowChatSound(true); Example JS API: Enable sounds for Visitors. */
          }
        };
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(se, s);
      })();
    </script>
<!-- end SnapEngage code-->

<!-- begin Mouseflow code-->
    <script type="text/javascript">
        var _mfq = _mfq || [];
        (function() {
        var mf = document.createElement("script");
        mf.type = "text/javascript"; mf.async = true;
        mf.src = "//cdn.mouseflow.com/projects/e936d07c-730f-4338-9f8c-4a6310af2e0a.js";
        document.getElementsByTagName("head")[0].appendChild(mf);
        })();
    </script>
<!-- end Mouseflow code-->

<!-- Facebook Pixel Code -->
    <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','//connect.facebook.net/en_US/fbevents.js');

        fbq('init', '166820737000993');
        fbq('track', "PageView");
        <?php if ($fbq) { echo $fbq; } ?>
    </script>
    <noscript>
        <img height="1" width="1" style="display:none" src="https://www.facebook.com/tr?id=166820737000993&ev=PageView&noscript=1" />
    </noscript>
<!-- End Facebook Pixel Code -->