<div class="table-wrapper order-items">
    <table class="data table table-order-items table-order-detail" id="my-orders-table" summary="<?php /* @escapeNotVerified */ echo __('Items Ordered'); ?>">
        <thead>
            <tr>
                <th class="col name"><?php /* @escapeNotVerified */ echo __('Item'); ?></th>
                <th class="col decription"><?php /* @escapeNotVerified */ echo __('Description'); ?></th>
                <th class="col material"><?php /* @escapeNotVerified */ echo __('Material'); ?></th>
                <th class="col size"><?php /* @escapeNotVerified */ echo __('Size'); ?></th>
                <th class="col price"><?php /* @escapeNotVerified */ echo __('Unit Price'); ?></th>
            </tr>
        </thead>
        <?php $_order = $block->getOrder(); ?>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_index = 0; ?>
        <?php $_count = $_items->count(); ?>
        <?php $_giftMessage = ''; ?>
        <tbody>
            <?php foreach ($_items as $_item): ?>
                <?php
                if ($_item->getParentItem()) {
                    continue;
                }
                ?>
                <?php echo $block->getItemHtml($_item); ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
                    <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                               id="order-item-gift-message-link-<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"
                               data-item-id="<?php /* @escapeNotVerified */ echo $_item->getId(); ?>">
                                   <?php /* @escapeNotVerified */ echo __('Gift Message'); ?>
                            </a>
                            <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId(); ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?php /* @escapeNotVerified */ echo __('Close'); ?>"
                                   aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"
                                   data-item-id="<?php /* @escapeNotVerified */ echo $_item->getId(); ?>"
                                   class="action close">
                                       <?php /* @escapeNotVerified */ echo __('Close'); ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ echo __('From'); ?></strong><?php echo $block->escapeHtml($_giftMessage->getSender()); ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ echo __('To'); ?></strong><?php echo $block->escapeHtml($_giftMessage->getRecipient()); ?></dt>
                                    <dd class="item-message"><?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_item); ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            <?php endforeach; ?>
        </tbody>
	</table>
	<table class="total-order">
        <tbody>
            <?php echo $block->getChildHtml('order_totals'); ?>
        </tbody>
	</table>
</div>
