<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php $_order = $block->getOrder(); ?>
<?php if ($_order): ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table width="525" align="center" border="0" cellpadding="0" cellspacing="0">

        <tbody>
            <tr>
                <td height="40" style="border-top: 1px solid #b2b2b2">&nbsp;</td>
            </tr>
            <?php
            foreach ($_items as $_item):
                if ($_item->getParentItem()) {
                    continue;
                }
                ?>
                <?php echo $block->getItemHtml($_item); ?>
            <?php endforeach; ?>

        </tbody>
        <tfoot class="order-totals">
            <tr>
                <td height="30" style="border-top: 1px solid #b2b2b2">&nbsp;</td>
            </tr>
    <?php echo $block->getChildHtml('order_totals'); ?>

        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()): ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage): ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo /* @escapeNotVerified */ __('Gift Message for this Order'); ?></h3>
                        <strong><?php echo /* @escapeNotVerified */ __('From'); ?>:</strong> <?php echo $block->escapeHtml($_giftMessage->getSender()); ?>
                        <br /><strong><?php echo /* @escapeNotVerified */ __('To'); ?>:</strong> <?php echo $block->escapeHtml($_giftMessage->getRecipient()); ?>
                        <br /><strong><?php echo /* @escapeNotVerified */ __('Message'); ?>:</strong>
                        <br /><?php echo $block->escapeHtml($_giftMessage->getMessage()); ?>
                    </td>
                </tr>
            </table>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
