<?php 
echo $this->getViewFileUrl();
$helper = $this->helper("\Ss\Designer\Helper\Data") ?>
<div class="popup popup-img hidden" id="wear-img">
    <div class="popup-content">
        <div class="image">
            <button type="button" name="close-1" id="close-1" class="icon icon-close" data-close="">
            </button>
            <img alt="img-big" src="<?php echo $this->getViewFileUrl('images/upload/img-998x500.png'); ?>"/>
        </div>
    </div>
</div>
