<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php

/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php /* @escapeNotVerified */ echo __('Sort By') ?></label>
    <div class="control">
        <select id="sorter" data-role="sorter" class="sorter-options">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <?php
                $suffixTitleAsc = __('Ascending');
                $suffixTitleDesc = __('Descending');
                switch ($_key) {
                    case \Ss\Theme\Helper\Attributes::SORT_ORDER_NAME:
                        $suffixTitleAsc = __("What's New");
                        break;
                    case \Ss\Theme\Helper\Attributes::SORT_ORDER_PRICE:
                        $suffixTitleAsc = __('Low to High');
                        $suffixTitleDesc = __('High to Low');
                        break;
                    default:
                        break;
                }

                if ($_key == \Ss\Theme\Helper\Attributes::SORT_ORDER_NAME):
                    ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_key . '_' . \Ss\Theme\Helper\Attributes::SORT_DIRECTION_ASC; ?>"
                    <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection() == \Ss\Theme\Helper\Attributes::SORT_DIRECTION_ASC): ?>
                                selected="selected"
                            <?php endif; ?>
                            >
                                <?php echo $suffixTitleAsc ?>
                    </option>
                <?php else: ?>
                    <option value="<?php /* @escapeNotVerified */ echo $_key . '_' . \Ss\Theme\Helper\Attributes::SORT_DIRECTION_ASC; ?>"
                    <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection() == \Ss\Theme\Helper\Attributes::SORT_DIRECTION_ASC): ?>
                                selected="selected"
                            <?php endif; ?>
                            >
                                <?php echo $block->escapeHtml(__($_order)) . ' ' . $suffixTitleAsc ?>
                    </option>

                    <option value="<?php /* @escapeNotVerified */ echo $_key . '_' . \Ss\Theme\Helper\Attributes::SORT_DIRECTION_DESC; ?>"
                    <?php if ($block->isOrderCurrent($_key) && $block->getCurrentDirection() == \Ss\Theme\Helper\Attributes::SORT_DIRECTION_DESC): ?>
                                selected="selected"
                            <?php endif; ?>
                            >
                                <?php echo $block->escapeHtml(__($_order)) . ' ' . $suffixTitleDesc ?>
                    </option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
    </div>
</div>
