
<?php

/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$designerHelper = $this->helper('Ss\Designer\Helper\Data');
$imageBefore = 'diamond_stud_before';
$imageAfter = 'diamond_stud_after';
$viewMode = 'grid';

// Get customer email
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerRepository = $objectManager->get('Magento\Customer\Api\CustomerRepositoryInterface');
$customerSession = $objectManager->create('Magento\Customer\Model\Session');
if ($customerSession->isLoggedIn()) {
    $customerId = $customerSession->getCustomerId();
    $customer = $customerRepository->getById($customerId);
    $customerEmail = $customer->getEmail();
}

// Get criteo
$criteo = $objectManager->create('Ss\Theme\Helper\Criteo');
$criteoIsEnable = $criteo->isEnable();
if ($criteoIsEnable) {
    $criteoAccount = $criteo->getAccount();
    $deviceType = $criteo->getDeviceType();
}

$productIds = [];
$listDesigner = [];
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>

    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                <?php
                $productIds[] = $_product->getId();
                $designerId = $_product->getSsDesigner();
                if (!empty($designerId)) {
                    if (!isset($listDesigner[$designerId])) {
                        $designer = $designerHelper->getDesignerById($designerId);
                        $listDesigner[$designerId] = $designer;
                    } else {
                        $designer = $listDesigner[$designerId];
                    }
                }
                ?>
                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info thumbnail" data-container="product-grid">
                    <?php
                    $productImageBefore = $block->getImage($_product, $imageBefore);
                    $productImageAfter = $block->getImage($_product, $imageAfter);
                    ?>
                    <?php // Product Image ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo image" tabindex="-1" data-item-id="<?php echo $_product->getId(); ?>">
                        <div class="before-wapper">
                            <?php echo $productImageBefore->toHtml() ?>
                        </div>
                        <div class="behind-wapper">
                            <?php echo $productImageAfter->toHtml() ?>
                        </div>
                    </a>
                    <div class="product details product-item-details">
                        <?php if (($designer)): ?>
                            <p class="author"><a href="<?php echo $designer->getUrl(); ?>" title="<?php echo $designer->getName(); ?>"><?php echo $designer->getName(); ?></a></p>
                        <?php endif; ?>

                        <p class="material product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                   <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </p>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
                <?php
            endforeach;
            unset($listDesigner);
            $listDesigner = [];
            ?>
        </ol>
    </div>
    <div class="toolbar-bottom">
        <a href="#" class="scroll-top"><?php echo __('Back to top'); ?></a>
        <?php echo $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
            {
            "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {}
            }
            }
        </script>
    <?php endif; ?>
<?php endif; ?>

<?php if ($criteoIsEnable): ?>
    <!-- Criteo -->
    <script type="text/javascript" src="//static.criteo.net/js/ld/ld.js" async="true"></script>
    <script type="text/javascript">
        window.criteo_q = window.criteo_q || [];
        window.criteo_q.push(
                {event: "setAccount", account: <?php echo $criteoAccount; ?> },
        {event: "setEmail", email: "<?php echo isset($customerEmail) ? $customerEmail : null; ?>"},
        {event: "setSiteType", type: "<?php echo $deviceType; ?>"},
        {event: "viewList", item:<?php echo Zend_Json::encode($productIds); ?>}
        );

        var accountIdTracking = <?php echo $criteoAccount; ?>;
        var emailIdTracking = "<?php echo isset($customerEmail) ? $customerEmail : null; ?>";
        var siteTypeTracking = "<?php echo $deviceType; ?>";
    </script>
    <!-- End Criteo -->
    <?php
 endif;
