<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<aside class="block account-nav">
    <p class="title">
        <a href="<?php echo $block->getUrl('customer/account/') ?>">
            <?php /* @escapeNotVerified */ echo __('My Account'); ?>
        </a>
    </p>
    <div class= "assistance-wrapper" data-collapse='{"notRunOn": "desktop", "isCollapseForMobile": true}'>
        <div class="collapse style-4" data-item>
            <div class="heading-collapse hidden-md-up" data-item-heading>
                <span>
                    <?php
                    foreach ($block->getLinks() as $link) :
                        if ($link->isCurrent() || $link->getIsHighlighted()) :
                            echo $link->getData('label');
                        endif;
                    endforeach;
                    ?>
                </span>
            </div>
            <div class="content-collapse" data-item-body>
                <ul class="nav items list-nav">
                    <?php echo $block->getChildHtml(); ?>
                </ul>
            </div>
        </div>
    </div>
</aside>