<div class="row login-form">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="title text-center"><?php /* @escapeNotVerified */ echo __('Forgot Your Login Information?') ?></h2>
        <form action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
              method="post"
              id="form-validate"
              name="sign-in-form"
              data-validate-form=""
              class="forgot-form"
              novalidate=""
              data-mage-init='{"validation":{}}'>
            <div class="form-group">
                <label><?php /* @escapeNotVerified */ echo __('Email address') ?></label>
                <input type="email" id="email" name="email" maxlength="125" class="input-1" placeholder="<?php /* @escapeNotVerified */ echo __('Email address') ?>" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" required="" data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>">
            </div>
            <div class="btn-group">
		<button type="submit" name="btn-submit-up" id="btn-submit-up" class="btn btn-block btn-black"><?php /* @escapeNotVerified */ echo __('reset') ?></button>
		<a href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>" title="<?php /* @escapeNotVerified */ echo __('Cancel') ?>" class="link-1"><?php /* @escapeNotVerified */ echo __('Cancel') ?></a>
            </div>
        </form>
    </div>
</div>
