<div class="col col-1">
    <h2 class="title"><?php echo __('Sign Up &amp; Start Loving.') ?></h2>
    <form action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
          method="post"
          name="sign-in-form"
          data-validate-form=""
          class="sign-up-form"
          novalidate=""
          id="form-validate"
          enctype="multipart/form-data"
          autocomplete="off">
        <input type="hidden" name="success_url" value="<?php /* @escapeNotVerified */ echo $block->getSuccessUrl() ?>">
        <input type="hidden" name="error_url" value="<?php /* @escapeNotVerified */ echo $block->getErrorUrl() ?>">

        <div class="row">
            <?php echo $block->getLayout()->createBlock('Ss\Customer\Block\Widget\Register\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>

            <div class="col-md-12">
                <div class="form-group">
                    <label for="email_address"><?php /* @escapeNotVerified */ echo __('Email address') ?></label>
                    <input type="email" id="email_address" name="email" maxlength="125" data-parsley-validate-email="" data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>" data-parsley-maxlength-message="<?php echo __("This value is too long. It should have %s characters or fewer."); ?>" data-parsley-validate-email-message="<?php echo __("Email format is incorrect. Only these characters are allowed: letters, numbers, and some special characters '@', '.', '_'"); ?>" class="input-1" placeholder="<?php /* @escapeNotVerified */ echo __('Email address') ?>" value="<?php echo $block->escapeHtml($block->getFormData()->getEmail()) ?>" required="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password"><?php /* @escapeNotVerified */ echo __('Password') ?></label>
                    <input type="password" id="password" name="password" minlength="8" maxlength="30" data-parsley-minlength-message="<?php echo __("Short passwords are easy to guess. Try one with at least %s characters."); ?>" data-parsley-maxlength-message="<?php echo __("This value is too long. It should have %s characters or fewer."); ?>" data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>" class="input-1" placeholder="<?php /* @escapeNotVerified */ echo __('Password') ?>" autocomplete="off" required="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label for="password-confirmation"><?php /* @escapeNotVerified */ echo __('Confirm Password') ?></label>
                    <input type="password" id="password-confirmation" minlength="8" maxlength="30" data-parsley-minlength-message="<?php echo __("Short passwords are easy to guess. Try one with at least %s characters."); ?>" data-parsley-maxlength-message="<?php echo __("This value is too long. It should have %s characters or fewer."); ?>" data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>" data-parsley-equalto-message="<?php echo __("These passwords don't match. Try again?"); ?>" name="password_confirmation" class="input-1" placeholder="<?php /* @escapeNotVerified */ echo __('Confirm Password') ?>" autocomplete="off" required="" data-parsley-equalto="#password">
                </div>
            </div>
        </div>
        <button type="submit" name="btn-submit-up" id="btn-submit-up" class="btn btn-block btn-black"><?php /* @escapeNotVerified */ echo __('Sign up') ?>
        </button>
        <div class="custom-checkbox">
            <input type="checkbox" id="is_subscribed" name="is_subscribed" value="1" checked="checked" data-parsley-multiple="checkbox-1">
            <label for="is_subscribed"><span><?php /* @escapeNotVerified */ echo __('Sign up to receive Stone &amp; Strand emails. From Capri to Los Angeles, we’ll take you on adventures with amazing jewels in tow.') ?> <a href="<?php echo $block->getUrl('privacy-policy'); ?>" title="<?php /* @escapeNotVerified */ echo __('Privacy') ?>"> <?php /* @escapeNotVerified */ echo __('Privacy') ?></a></span></label>
        </div>
    </form>
</div>
