<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Resetpassword $block */
?>
<div class="row login-form">
    <div class="col-md-6 col-md-offset-3">
        <h2 class="title text-center"><?php /* @escapeNotVerified */ echo __('Set a New Password') ?></h2>
        <form action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/resetpasswordpost', ['_query' => ['id' => $block->getCustomerId(), 'token' => $block->getResetPasswordLinkToken()]]); ?>"
              method="post"
              <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?>
              id="form-validate"
              class="form password reset sign-up-form"
              data-validate-form=""
              data-mage-init='{"validation":{}}'>
            <div class="form-group">
                <label for="password"><?php /* @escapeNotVerified */ echo __('New Password'); ?></label>
                <input type="password" class="input-1" name="password" id="password" required="" autocomplete="off">
            </div>
            <div class="form-group">
                <label for="password-confirmation"><?php /* @escapeNotVerified */ echo __('Confirm New Password'); ?></label>
                <input type="password" class="input-1" name="password_confirmation" id="password-confirmation" required="" autocomplete="off">
            </div>
            <button type="submit" name="btn-submit-up" id="btn-submit-up" class="btn btn-block btn-black"><?php /* @escapeNotVerified */ echo __('Set a New Password') ?></button>
        </form>
    </div>
</div>

