<div class="col-md-6 required">
    <div class="form-group">
        <label for="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>">
            <?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>
        </label>

        <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('firstname') ?>"
               name="<?php /* @escapeNotVerified */ echo $block->getFieldName('firstname') ?>"
               value="<?php echo $block->escapeHtml($block->getObject()->getFirstname()) ?>"
               placeholder="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('firstname') ?>"
               class="input-1" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>
               required="" maxlength="125"
               data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>"
               data-parsley-maxlength-message="<?php echo __("This value is too long. It should have %s characters or fewer."); ?>">
    </div>
</div>
<div class="col-md-6 required">
    <div class="form-group">
        <label for="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>">
            <?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>
        </label>
        <input type="text" id="<?php /* @escapeNotVerified */ echo $block->getFieldId('lastname') ?>"
               name="<?php /* @escapeNotVerified */ echo $block->getFieldName('lastname') ?>"
               value="<?php echo $block->escapeHtml($block->getObject()->getLastname()) ?>"
               placeholder="<?php /* @escapeNotVerified */ echo $block->getStoreLabel('lastname') ?>"
               class="input-1" <?php /* @escapeNotVerified */ echo $block->getFieldParams() ?>
               required="" maxlength="125"
               data-parsley-required-message="<?php echo __("You can't leave this empty."); ?>"
               data-parsley-maxlength-message="<?php echo __("This value is too long. It should have %s characters or fewer."); ?>">
    </div>
</div>
