<div class="block-banner banner-e style-1">
    <div class="grid-fluid">
        <div class="thumbnail"><a href="#" title="Never Boring. Totally Reliable." class="image"><img src="<?php echo $this->getViewFileUrl('images/upload/BannerE-Ampersand.jpg'); ?>" alt="image"/></a>
        </div>
        <h2 class="banner-title"><a href="#" title="Never Boring. Totally Reliable.">Never Boring. Totally Reliable.</a>
        </h2>
    </div>
</div>