<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Create account form template
/* @var $block \Magento\Rma\Block\Form\Renderer\Select */
?>
<div class="field <?php echo $block->getHtmlId()?><%- data._index_ %><?php if ($block->isRequired()) { echo ' required'; } ?>">
    <label for="items:<?php echo $block->getHtmlId()?><%- data._index_ %>" class="label"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?><?php if ($block->isRequired()) : ?></span><span class="mandatory-field">*</span><?php endif; ?></label>
    <div class="control">
        <select id="items:<?php echo $block->getHtmlId()?><%- data._index_ %>" name="items[<%- data._index_ %>][<?php /* @escapeNotVerified */ echo $block->getFieldName()?>]"<?php if ($block->getFieldName() == 'reason'): ?> data-args='{"index":<%- data._index_ %>}' <?php endif; ?> <?php if ($block->isRequired()) : ?>required data-parsley-required-message="<span class='img-icon icon-error' data-toggle-error>&nbsp;</span><p class='hidden'><?php echo __("You can't leave this empty."); ?></p>"<?php endif; ?>>
            <?php foreach ($block->getOptions() as $option): if (! empty($option['value'])): ?>
                <option value="<?php /* @escapeNotVerified */ echo $option['value']?>"<?php if ($option['value'] == $block->getValue()):?> selected="selected"<?php endif;?>><?php echo $block->escapeHtml($option['label'])?></option>
            <?php endif; endforeach;?>
            <?php if ($block->getFieldName() == 'reason'): ?>
                <?php $attribute = $block->getAttribute('reason_other'); ?>
                <?php if ($attribute): ?>
                    <option value="other"<?php if ($option['value'] == 'other'):?> selected="selected"<?php endif;?>><?php echo $block->escapeHtml($attribute->getStoreLabel())?></option>
                <?php endif; ?>
            <?php endif; ?>
        </select>
    </div>
</div>
