<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation\State
 */
$isFilterDesignerPage = $block->getRequest()->getParam(\Ss\Theme\Helper\Data::IS_FILTER_DESIGNER_PAGE, FALSE);
$designerHelper = $this->helper('Ss\Designer\Helper\Data');
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
    <div class="filter-current">
        <strong class="block-subtitle filter-current-subtitle"
                role="heading"
                aria-level="2"
                data-count="<?php echo count($_filters); ?>"><?php /* @escapeNotVerified */ echo __('Now Shopping by') ?></strong>
        <ol class="items">
            <?php foreach ($_filters as $_filter): ?>
                <?php
                $requestVar = $_filter->getFilter()->getRequestVar();
                if (($isFilterDesignerPage && $requestVar == \Ss\Designer\Model\Designer::ATTRIBUTE_CODE) || $requestVar == \Ss\ProductSale\Helper\Data::PRODUCT_SALE_FILTER) {
                    continue;
                }
                ?>
                <li class="item">                
                    <?php
                    $clearLinkUrl = $_filter->getClearLinkUrl();
                    $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                    if ($clearLinkUrl):
                        ?>
                        <a class="action previous" href="<?php /* @escapeNotVerified */ echo $_filter->getRemoveUrl() ?>"
                           title="<?php /* @escapeNotVerified */ echo __('Previous') ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Previous') ?></span>
                        </a>
                        <a class="action remove"
                           title="<?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                           href="<?php /* @escapeNotVerified */ echo $clearLinkUrl ?>">
                            <span><?php echo $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?></span>
                        </a>
                    <?php else: ?>
                        <?php
                        $filterUrl = $_filter->getRemoveUrl();
                        if ($isFilterDesignerPage && $requestVar == \Ss\Designer\Model\Designer::PARAM_FILTER_CATEGORY) {
                            $filterUrl = $designerHelper->getFilterCategoryUrl($requestVar, NULL);
                        }
                        ?>
                        <a class="action remove" href="<?php /* @escapeNotVerified */ echo $filterUrl; ?>"
                           title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Remove')) . " " . $currentFilterName; ?>">
                            <span><?php /* @escapeNotVerified */ echo __('Remove This Item') ?></span>
                        </a>
                    <?php endif; ?>

                    <span class="filter-label"><?php echo $block->escapeHtml(__($_filter->getName())); ?> : </span>
                    <span class="filter-value"><?php /* @escapeNotVerified */ echo $block->stripTags($_filter->getLabel()) ?></span>
                </li>

            <?php endforeach; ?>
        </ol>
    </div>
<?php endif; ?>
