<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/**
 * @var \Magento\Theme\Block\Html\Header\Logo $block
 */

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$themeHelper = $objectManager->create("\Ss\Theme\Helper\Data");
$logoUrl = '';
if($themeHelper->checkIsCustomerGroupVip()){
    $logoUrl = $themeHelper->getCustomerGroupVipLogo();
}
if(empty($logoUrl)){
    $logoUrl = $block->getLogoSrc();
}

?>
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt(); ?>

<a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
    <img style="display: inline;"
         src="<?php /* @escapeNotVerified */ echo $logoUrl ?>"
         alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
         <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
         <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
         />
</a>
