<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$themeHelper = $objectManager->create("Ss\Theme\Helper\Data");
$maxQty = $themeHelper->getMaxQtyProduct();
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()): ?>
            <div class="field qty select-group">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></label>
                <div class="control select">
                    <select name="qty" id="qty" class="input-text qty" data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>" title="<?php /* @escapeNotVerified */ echo __('Quantity') ?>">
                        <?php
                        $i = $block->getProductDefaultQty() * 1;
                        do {
                            ?>
                            <option value="<?php echo $i ?>">
                                <?php
                                echo $i;
                                $i ++;
                                ?>
                            </option>
                            <?php
                        }while ( $i <= $maxQty)
                        ?>
                    </select>
                </div>
            </div>
        <?php endif; ?>

    </div>
</div>
<?php else: ?>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="field qty select-group">
                <label class="label" for="qty"><span><?php /* @escapeNotVerified */ echo __('Quantity') ?></span></label>
                <div class="control select">
                    <select name="qty" id="qty" class="input-text qty" title="<?php /* @escapeNotVerified */ echo __('Quantity') ?>">
                        <option value="sold-out"><?php echo __('Sold Out') ?></option>
                    </select>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php


?>

<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script>
    require([
        'jquery',
        'mage/mage',
        'Magento_Catalog/product/view/validation',
        'Magento_Catalog/js/catalog-add-to-cart'
    ], function ($) {
        'use strict';

        $('#product_addtocart_form').mage('validation', {
            radioCheckboxClosest: '.nested',
            submitHandler: function (form) {
                var widget = $(form).catalogAddToCart({
                    bindSubmit: false
                });

                widget.catalogAddToCart('submitForm', $(form));

                return false;
            }
        });
    });
</script>
<?php endif; ?>