<div class="block-banner testimonials-block">
    <div class="grid-fluid">
        <h2 class="title">testimonials</h2>
        <div data-slick-slider="{&quot;isNotHaveImg&quot;: true, &quot;isCenterArrowsMobile&quot;: false}" class="slider list-testimonials">
            <div class="item">
                <div class="content">
                    <blockquote>“..one of the best experiences I have ever had. Selection, ease, beautiful shipping presentation of items, stress-free return of one of the items, not to mention the personal notes added up to the perfect shopping experience. Believe me, that does not happen often.”</blockquote>
                    <p class="author">diane</p>
                    <p class="location">Birmingham, Michigan</p>
                </div>
            </div>
            <div class="item">
                <div class="content">
                    <blockquote>“..one of the best experiences I have ever had. Selection, ease, beautiful shipping presentation of items, stress-free return of one of the items, not to mention the personal notes added up to the perfect shopping experience. Believe me, that does not happen often.”</blockquote>
                    <p class="author">diane</p>
                    <p class="location">Birmingham, Michigan</p>
                </div>
            </div>
            <div class="item">
                <div class="content">
                    <blockquote>“..one of the best experiences I have ever had. Selection, ease, beautiful shipping presentation of items, stress-free return of one of the items, not to mention the personal notes added up to the perfect shopping experience. Believe me, that does not happen often.”</blockquote>
                    <p class="author">diane</p>
                    <p class="location">Birmingham, Michigan</p>
                </div>
            </div>
        </div>
    </div>
</div>